name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para obtener todos los tags
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build for multiple platforms
        run: |
          make build-all

      # - name: Generate changelog
      #   id: changelog
      #   run: |
      #     # Obtener los commits desde el último tag
      #     previous_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
      #     if [ -z "$previous_tag" ]; then
      #       git log --pretty=format:"* %s" > CHANGELOG.md
      #     else
      #       git log --pretty=format:"* %s" $previous_tag..HEAD > CHANGELOG.md
      #     fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
          # name: Release ${{ env.VERSION }}
          # # body_path: CHANGELOG.md
          # files: |
          #   dist/*
          # draft: false
          # prerelease: false